// Allowlisted domains that should NEVER be blocked
const ALLOWED_DOMAINS = new Set([
  'tuamaeaquelaursa.com',
]);

// ~500 known disposable email domains
const DISPOSABLE_DOMAINS = new Set([
  // Major disposable email services
  'tempmail.com', 'temp-mail.org', 'temp-mail.io', 'temp-mail.de',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamail.de', 'guerrillamail.biz',
  'guerrillamailblock.com', 'grr.la', 'sharklasers.com', 'pokemail.net', 'spam4.me',
  'yopmail.com', 'yopmail.fr', 'yopmail.net', 'yopmail.gq',
  'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com',
  'throwaway.email', 'throwaway.me',
  '10minutemail.com', '10minutemail.net', '10minutemail.org', '10minutemail.co.za',
  '10minutemail.de', '10minutemail.be', '10minutemail.eu',
  'tempail.com', 'tempr.email', 'tempalias.com', 'tempinbox.com',
  'disposableemailaddresses.emailmiser.com',
  
  // Popular services
  'dispostable.com', 'mailnesia.com', 'maildrop.cc', 'mailcatch.com',
  'mailnull.com', 'mailscrap.com', 'mailsac.com', 'mailslurp.com',
  'mohmal.com', 'mohmal.im', 'mohmal.in', 'mohmal.tech',
  'burnermail.io', 'burnmail.ca',
  'trashmail.com', 'trashmail.org', 'trashmail.net', 'trashmail.me', 'trashmail.at', 'trash-mail.com', 'trash-mail.at',
  'fakeinbox.com', 'fakemail.net', 'fakemail.fr',
  'getairmail.com', 'getnada.com', 'gettempmail.com',
  'harakirimail.com', 'haltospam.com',
  'mailtemp.info', 'mailtemp.net',
  'tempmailo.com', 'tempmailer.com', 'tempmailer.de',
  'spambox.us', 'spamfree24.org', 'spamgourmet.com', 'spamgourmet.net',
  'crazymailing.com', 'deadaddress.com',
  'emailondeck.com', 'emailfake.com', 'emkei.cz',
  'filzmail.com', 'fixmail.tk',
  'flitmail.com', 'flymail.tk',
  'inboxalias.com', 'inboxbear.com', 'inboxclean.com', 'inboxclean.org',
  'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'kasmail.com', 'koszmail.pl',
  'kurzepost.de', 'lastmail.co',
  'lroid.com', 'lortemail.dk',
  'mailforspam.com', 'mailfree.ga', 'mailfree.gq', 'mailfree.ml',
  'mailme.ir', 'mailme.lv', 'mailmetrash.com',
  'mailmoat.com', 'mailnator.com',
  'mailtemporaire.com', 'mailtemporaire.fr',
  'meltmail.com', 'mintemail.com',
  'mytemp.email', 'mytrashmail.com',
  'nomail.xl.cx', 'nospam.ze.tc', 'nospamfor.us',
  'nowmymail.com', 'objectmail.com',
  'obobbo.com', 'odaymail.com',
  'one-time.email', 'oneoffemail.com',
  'otherinbox.com', 'owlpic.com',
  'pjjkp.com', 'plexolan.de',
  'proxymail.eu', 'putthisinyouremail.com',
  'receiveee.com', 'regbypass.com', 'regbypass.comsafe-mail.net',
  'rklips.com', 'rmqkr.net',
  'royal.net', 'rtrtr.com',
  'safersignup.de', 'safetymail.info', 'safetypost.de',
  'saynotospams.com', 'scatmail.com',
  'selfdestructingmail.com', 'shortmail.net',
  'skeefmail.com', 'slaskpost.se', 'slipry.net',
  'soodonims.com', 'sofimail.com',
  'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru',
  'spamcannon.com', 'spamcannon.net',
  'spamcero.com', 'spamcon.org',
  'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org',
  'spamday.com', 'spamex.com',
  'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq', 'spamfighter.ml', 'spamfighter.tk',
  'spamhereplease.com', 'spamhole.com',
  'spaml.com', 'spaml.de',
  'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spamslicer.com',
  'spamspot.com', 'spamstack.net',
  'spamthis.co.uk', 'spamtrail.com', 'spamtrap.ro',
  'superrito.com', 'suremail.info',
  'teleworm.us', 'thankyou2010.com', 'thankyou2020.com',
  'thisisnotmyrealemail.com', 'throwam.com',
  'tmail.ws', 'tmailinator.com',
  'tradermail.info', 'trbvm.com', 'trbvn.com',
  'turual.com', 'twinmail.de',
  'tyldd.com', 'uggsrock.com',
  'upliftnow.com', 'uplipht.com',
  'venompen.com', 'veryrealemail.com',
  'vidchart.com', 'viditag.com',
  'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org',
  'vomoto.com', 'vpn.st',
  'vsimcard.com', 'vubby.com',
  'wasteland.rfc822.org', 'webemail.me',
  'weg-werf-email.de', 'wegwerf-email-addressen.de', 'wegwerf-emails.de',
  'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'wh4f.org', 'whatiaas.com', 'whatpaas.com',
  'whyspam.me', 'wickmail.net', 'wilemail.com',
  'willhackforfood.biz', 'willselfdestruct.com',
  'winemaven.info', 'wronghead.com',
  'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu', 'xagloo.com',
  'xemaps.com', 'xents.com',
  'xjoi.com', 'xmaily.com',
  'xoxy.net', 'xyzfree.net',
  'yapped.net', 'yepmail.net',
  'yogamaven.com', 'yomail.info',
  'yopweb.com', 'youmailr.com',
  'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'zehnminutenmail.de', 'zippymail.info',
  'zoaxe.com', 'zoemail.org', 'zomg.info',
  
  // Additional well-known services
  'disposable.email', 'disposableaddress.com', 'discard.email',
  'discardmail.com', 'discardmail.de',
  'dropmail.me', 'emailna.co', 'emailna.life',
  'emlhub.com', 'emlpro.com',
  'fakemailgenerator.com', 'fastmail.in',
  'findu.pl', 'flirtyblogger.com',
  'getonemail.com', 'getonemail.net',
  'ghosttexter.de', 'girlsundertheinfluence.com',
  'gishpuppy.com', 'grandmamail.com', 'grandmasmail.com',
  'great-host.in', 'greensloth.com',
  'gsrv.co.uk', 'haqed.com',
  'hidemail.de', 'hidzz.com',
  'hotpop.com', 'hulapla.de',
  'ieatspam.eu', 'ieatspam.info',
  'imails.info', 'imgof.com',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'insorg-mail.info', 'ipoo.org',
  'irish2me.com', 'iwi.es',
  'jnxjn.com', 'jobbikszyer.hu',
  'jourrapide.com',
  'keepmymail.com', 'killmail.com', 'killmail.net',
  'klzlk.com', 'kook.ml',
  'lackmail.net', 'lakelivinglife.com',
  'landmail.co', 'letthemeatspam.com',
  'lhsdv.com', 'lifebyfood.com',
  'link2mail.net', 'litedrop.com',
  'llogin.ru', 'logamail.com',
  'lol.ovpn.to', 'lookugly.com',
  'lr78.com', 'lru.me',
  'lukop.dk', 'luv2.us',
  'm21.cc', 'maboard.com',
  'mail-temporaire.fr', 'mail.by',
  'mail.mezimages.net', 'mail2rss.org',
  'mail333.com', 'mail4trash.com',
  'mailbidon.com', 'mailblocks.com',
  'mailbucket.org', 'mailcat.biz',
  'mailcatch.com', 'mailde.de', 'mailde.info',
  'maildx.com', 'maileater.com',
  'mailexpire.com', 'mailfa.tk',
  'mailfree.ga', 'mailfreeonline.com',
  'mailfs.com', 'mailguard.me',
  'mailhazard.com', 'mailhazard.us',
  'mailhz.me', 'mailimate.com',
  'mailin8r.com', 'mailinater.com',
  'mailincubator.com', 'mailismagic.com',
  'mailjunk.cf', 'mailjunk.ga', 'mailjunk.gq', 'mailjunk.ml', 'mailjunk.tk',
  'mailmate.com', 'mailme.ir',
  'mailme24.com', 'mailmoth.com',
  'mailnull.com', 'mailorg.org',
  'mailpick.biz', 'mailproxsy.com',
  'mailquack.com', 'mailrock.biz',
  'mailscrap.com', 'mailshell.com',
  'mailsiphon.com', 'mailslite.com',
  'mailtemp.info', 'mailtothis.com',
  'mailtrash.net', 'mailtv.net', 'mailtv.tv',
  'mailzilla.com', 'mailzilla.org',
  'makemetheking.com', 'manifestgenerator.com',
  'manybrain.com', 'mbx.cc',
  'mega.zik.dj', 'meinspamschutz.de',
  'messagebeamer.de', 'mezimages.net',
  'mfsa.info', 'mfsa.ru',
  'mierdamail.com', 'ministry-of-silly-walks.de',
  'mintemail.com', 'misterpinball.de',
  'mmmmail.com', 'moakt.com', 'moakt.ws',
  'mobileninja.co.uk', 'moburl.com',
  'moncourrier.fr.nf', 'monemail.fr.nf',
  'monmail.fr.nf', 'monumentmail.com',
  'msa.minet.io', 'mt2015.com',
  'mx0.wwwnew.eu', 'my10minutemail.com',
  'mycard.net.ua', 'mycleaninbox.net',
  'mymail-in.net', 'mypacks.net',
  'mypartyclip.de', 'myphantom.com',
  'mysamp.de', 'myspaceinc.com',
  'myspaceinc.net', 'myspaceinc.org',
  'myspacepimpedup.com', 'mytempemail.com',
  'mytempmail.com', 'mytrashmail.com',
  'nabala.com', 'neomailbox.com',
  'nervmich.net', 'nervtansen.de',
  'netmails.com', 'netmails.net',
  'neverbox.com', 'no-spam.ws',
  'noblepioneer.com', 'nobulk.com',
  'noclickemail.com', 'nogmailspam.info',
  'nomail.pw', 'nomail.xl.cx',
  'nomail2me.com', 'nomorespamemails.com',
  'nonspam.eu', 'nonspammer.de',
  'noref.in', 'nospam.wins.com.br',
  'nospam.ze.tc', 'nospam4.us',
  'nospamfor.us', 'nospammail.net',
  'nospamthanks.info', 'nothingtoseehere.ca',
  'nowmymail.com', 'nurfuerspam.de',
  'nus.edu.sg', 'nwldx.com',
  'objectmail.com', 'obobbo.com',
  'odnorazovoe.ru', 'oneoffemail.com',
  'onewaymail.com', 'oopi.org',
  'ordinaryamerican.net', 'otherinbox.com',
  'ourklips.com', 'outlawspam.com',
  'ovpn.to', 'owlpic.com',
  'pancakemail.com', 'pimpedupmyspace.com',
  'pjjkp.com', 'plexolan.de',
  'pookmail.com', 'privacy.net',
  'privy-mail.com', 'privymail.de',
  'proxymail.eu', 'prtnx.com',
  'prtz.eu', 'pubmail.io',
  'punkass.com', 'putthisinyouremail.com',
  'pwrby.com', 'q314.net',
  'qisdo.com', 'qisoa.com',
  'quickinbox.com', 'rcpt.at',
  'reallymymail.com', 'receiveee.com',
  'recode.me', 'recursor.net',
  'recyclemail.dk', 'regbypass.com',
  'rejectmail.com', 'reliable-mail.com',
  'rhyta.com', 'rklips.com',
  'rmqkr.net', 'rppkn.com',
  'rtrtr.com', 'rubyridge.com',
  's0ny.net', 'safe-mail.net',
  'safersignup.de', 'safetymail.info',
  'safetypost.de', 'sandelf.de',
  'saynotospams.com', 'scatmail.com',
  'schafmail.de', 'selfdestructingmail.com',
  'sendspamhere.com', 'shiftmail.com',
  'shitmail.me', 'shitmail.org',
  'shortmail.net', 'sibmail.com',
  'sinnlos-mail.de', 'siteposter.net',
  'skeefmail.com', 'slaskpost.se',
  'slipry.net', 'slopsbox.com',
  'slowslow.de', 'slutty.horse',
  'smashmail.de', 'sms.at',
  'snakemail.com', 'sneakemail.com',
  'snkmail.com', 'sofimail.com',
  'sofort-mail.de', 'softpls.asia',
  'sogetthis.com', 'soisz.com',
  'solvemail.info', 'soodonims.com',
  'spam.la', 'spam.su',
  'spamavert.com', 'spambob.com',
  'spambox.info', 'spambox.irishspringrealty.com',
  'spambox.us', 'spamcannon.com',
  'spamcero.com', 'spamcon.org',
  'spamcorptastic.com', 'spamcowboy.com',
  'spamday.com', 'spamex.com',
  'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
  'spamhereplease.com', 'spamhole.com',
  'spamify.com', 'spaml.com',
  'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spamslicer.com',
  'spamspot.com', 'spamstack.net',
  'spamthis.co.uk', 'spamtrail.com',
  'speed.1s.fr', 'supergreatmail.com',
  'supermailer.jp', 'superrito.com',
  'suremail.info', 'svk.jp',
  'sweetxxx.de', 'tafmail.com',
  'tagyoureit.com', 'talkinator.com',
  'tapchicuoihoi.com', 'teewars.org',
  'teleworm.com', 'teleworm.us',
  'temp.emeraldcraft.com', 'temp.headstrong.de',
  'tempemail.biz', 'tempemail.co.za',
  'tempemail.com', 'tempemail.net',
  'tempinbox.co.uk', 'tempinbox.com',
  'tempmail.eu', 'tempmail.it',
  'tempmail2.com', 'tempmaildemo.com',
  'tempmailer.com', 'tempmailer.de',
  'tempomail.fr', 'temporarily.de',
  'temporarioemail.com.br', 'temporaryemail.net',
  'temporaryemail.us', 'temporaryforwarding.com',
  'temporaryinbox.com', 'temporarymailaddress.com',
  'thankdog.com', 'thankyou2010.com',
  'thc.st', 'thecriminals.com',
  'thisisnotmyrealemail.com', 'thismail.net',
  'throwawayemailaddress.com', 'tilien.com',
  'tittbit.in', 'tmail.ws',
  'tmailinator.com', 'toiea.com',
  'toomail.biz', 'tradermail.info',
  'trash2009.com', 'trash2010.com', 'trash2011.com',
  'trashdevil.com', 'trashdevil.de',
  'trashemail.de', 'trashmail.at',
  'trashmail.io', 'trashmail.ws',
  'trashmailer.com', 'trashymail.com', 'trashymail.net',
  'trbvm.com', 'trbvn.com',
  'trialmail.de', 'trickmail.net',
  'trillianpro.com', 'turual.com',
  'twinmail.de', 'tyldd.com',
  'ubismail.net', 'uggsrock.com',
  'umail.net', 'upliftnow.com',
  'uplipht.com', 'venompen.com',
  'veryrealemail.com', 'viditag.com',
  'viewcastmedia.com', 'vomoto.com',
  'vpn.st', 'vsimcard.com',
  'vubby.com', 'w3internet.co.uk',
  'walkmail.net', 'wasteland.rfc822.org',
  'watchfull.net', 'webemail.me',
  'webm4il.info', 'wegwerfadresse.de',
  'wegwerfemail.de', 'wegwerfmail.de',
  'wegwerfmail.net', 'wegwerfmail.org',
  'wetrainbayarea.com', 'wetrainbayarea.org',
  'wh4f.org', 'whatiaas.com',
  'whatpaas.com', 'whyspam.me',
  'wickmail.net', 'wilemail.com',
  'willhackforfood.biz', 'willselfdestruct.com',
  'winemaven.info', 'wronghead.com',
  'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu', 'xagloo.com',
  'xemaps.com', 'xents.com',
  'xjoi.com', 'xmaily.com',
  'xoxy.net', 'xyzfree.net',
  'yapped.net', 'yepmail.net',
  'yogamaven.com', 'yomail.info',
  'yopmail.com', 'yopmail.fr',
  'youmailr.com', 'ypmail.webarnak.fr.eu.org',
  'yuurok.com', 'zehnminutenmail.de',
  'zippymail.info', 'zoaxe.com',
  'zoemail.org', 'zomg.info',
  
  // Additional popular ones
  'nada.email', 'nada.ltd', 'sharklasers.com',
  'guerrillamail.info', 'grr.la', 'guerrillamailblock.com',
  'cuvox.de', 'armyspy.com', 'dayrep.com', 'einrot.com',
  'fleckens.hu', 'gustr.com', 'jourrapide.com', 'rhyta.com',
  'superrito.com', 'teleworm.us',
  'maildrop.cc', 'mailnesia.com',
  'binkmail.com', 'bobmail.info',
  'chammy.info', 'devnullmail.com',
  'disbox.net', 'disbox.org',
  'emailigo.de', 'emailisvalid.com',
  'emailspam.cf', 'emailspam.ga', 'emailspam.gq', 'emailspam.ml', 'emailspam.tk',
  'emeil.in', 'emeil.ir',
  'ephemail.net', 'etranquil.com', 'etranquil.net', 'etranquil.org',
  'evopo.com', 'ezfill.com',
  'getairmail.com', 'getnada.com',
  'imgof.com', 'imstations.com',
  'inboxkitten.com', 'incognitomail.org',
  'ipoo.org', 'irish2me.com',
]);

// Suspicious patterns in domain names
const SUSPICIOUS_PATTERNS = [
  /tempmail/i,
  /temp-mail/i,
  /temp\.mail/i,
  /throwaway/i,
  /throw-away/i,
  /disposable/i,
  /10minute/i,
  /10min/i,
  /minutemail/i,
  /fakemail/i,
  /fake-mail/i,
  /fakeinbox/i,
  /trashmail/i,
  /trash-mail/i,
  /spammail/i,
  /spam-mail/i,
  /guerrillamail/i,
  /guerrilla-mail/i,
  /mailinator/i,
  /yopmail/i,
  /wegwerf/i,
  /einweg/i,
  /temporarymail/i,
  /temporary-mail/i,
  /tempinbox/i,
  /temp-inbox/i,
  /burnermail/i,
  /burner-mail/i,
  /nospam/i,
  /no-spam/i,
  /spamfree/i,
  /spam-free/i,
  /mailtemp/i,
  /mail-temp/i,
  /junkmail/i,
  /junk-mail/i,
  /discard\.email/i,
  /discard-email/i,
  /throwawaym/i,
];

/**
 * Check if an email address uses a known disposable/temporary email domain.
 * Returns true if the email is from a disposable domain (should be blocked).
 * Returns false if the email is safe to use.
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes('@')) return false;

  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;

  // Check allowlist first - these are NEVER blocked
  if (ALLOWED_DOMAINS.has(domain)) return false;

  // Check against known disposable domains
  if (DISPOSABLE_DOMAINS.has(domain)) return true;

  // Check suspicious patterns in domain name
  for (const pattern of SUSPICIOUS_PATTERNS) {
    if (pattern.test(domain)) return true;
  }

  return false;
}
